// <auto-generated />
using System;
using ECommerce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529055326_NombreDeLaMigracion")]
    partial class NombreDeLaMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b24e0f7f-9877-42b6-a769-0327d02adf08"),
                            CategoryId = new Guid("6473a65c-1bd6-45e6-bf55-89a290671d4b"),
                            CreatedAt = new DateTime(2026, 5, 29, 5, 53, 25, 297, DateTimeKind.Utc).AddTicks(3286),
                            Description = "Laptop gaming i7",
                            Name = "Laptop Dell",
                            Price = 1200.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("8036167c-c2d5-4301-9f68-bf2fb0467a4e"),
                            CategoryId = new Guid("9975b4a9-53e8-4dc7-9a18-a2231caff5d1"),
                            CreatedAt = new DateTime(2026, 5, 29, 5, 53, 25, 297, DateTimeKind.Utc).AddTicks(3290),
                            Description = "Celular Apple",
                            Name = "Iphone 15",
                            Price = 899.99m,
                            Stock = 8
                        },
                        new
                        {
                            Id = new Guid("b9a444e6-16b9-44c4-8d08-26c0f89bffdc"),
                            CategoryId = new Guid("74d3ef0e-6020-4181-92ce-dc52277abef1"),
                            CreatedAt = new DateTime(2026, 5, 29, 5, 53, 25, 297, DateTimeKind.Utc).AddTicks(3293),
                            Description = "Casco integral",
                            Name = "Casco Moto",
                            Price = 85.50m,
                            Stock = 25
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
